[package]
name = "interpreter"
version = "0.1.0"
authors = ["candiel-z <candiel_z@yahoo.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
